apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
    service: app1
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: app1
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      version: v1
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      containers:
      - image: loftkun/simple-msa-app1
        imagePullPolicy: IfNotPresent
        name: app1
        resources: {}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
    service: app2
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: app2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      containers:
      - image: loftkun/simple-msa-app2
        imagePullPolicy: IfNotPresent
        name: app2
        resources: {}
        ports:
        - containerPort: 5000